### ISSUE TITLE
Impl support for translating attribute expressions into pinot queries

### ISSUE THREAD

**Issue by kotharironak** [hypertrace/query-service#100]
Based on new the [discussion](https://github.com/hypertrace/hypertrace-ui/issues/1099#issuecomment-968609440), for the new `AttributeExpression` translate it to appropriate Pinot queries.

As part of this ticket, address the conversation to pinot queries for QS having `AttributeExpression`
- selection
- groupby
- order by
- filter

e.g of with `AttributeExpression` with subpath having filter clause
```
childFilter {
        lhs {
          AttributeExpression {
            attributeId: "API_TRACE.tags"
            subPath" "span.kind"
          }
        }
        operator: EQ
        rhs {
          literal {
            value {
              valueType: STRING
              string: "server"
            }
          }
        }
}
```

Pinot Query (selection, and limit are assumed), see filter expression for tags attribute for reference
```
select mapValue(tags__KEYS,'span.kind',tags__VALUES) FROM spanEventView 
WHERE tenant_id = '__default'  
AND mapValue(tags__KEYS,'span.kind',tags__VALUES) != ''
AND by mapValue(tags__KEYS,'span.kind',tags__VALUES) = 'server'
limit 10000
```

### Reference:
See the reference UI ticket - hypertrace/hypertrace-ui#1099 and discussion.

<hr>

As a part of this issue, the following subtasks would be required : 

- [x] #104
- [x] #105

Few follow up PR's which will be required are : 
- [x] #122
- [x] #109
- [x] Replacing columnIdentifiers with attributeExpressions in preprocessing (tracked in https://github.com/hypertrace/query-service/pull/129)

**Comment by sarthak77** [comment]
We will currently have these 2 draft PR's stay as it is and they will be later merged appropriately :

- https://github.com/hypertrace/query-service/pull/96
- https://github.com/hypertrace/query-service/pull/97

Doing this so that the whole process becomes simple and we will start with **simple attributes** first followed by the **complex attributes**.

**Comment by sarthak77** [comment]
I think the above 2 draft PR's will have to be eventually discarded as they contain only few changes but there are a lot of merge conflicts. Will incorporate their changes in new PR.
